# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: vehiclessafetyinspection
services:
  app:
    image: vehiclessafetyinspection
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521:vehiclesSafetyInspection
      - SPRING_LIQUIBASE_URL=jdbc:oracle:thin:@oracle:1521:vehiclesSafetyInspection
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8090:8090
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8090/management/health']
      interval: 5s
      timeout: 5s
      retries: 40
